# Generated by Django 3.1.7 on 2021-03-17 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.TextField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('courier', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='candy_delivery_app.courier')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('weight', models.FloatField()),
                ('region', models.IntegerField()),
                ('assign_time', models.DateTimeField(default=None, null=True)),
                ('complete_time', models.DateTimeField(default=None, null=True)),
                ('courier', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='candy_delivery_app.courier')),
            ],
        ),
        migrations.CreateModel(
            name='Interval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('courier', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='candy_delivery_app.courier')),
                ('order', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='candy_delivery_app.order')),
            ],
        ),
    ]
