# Generated by Django 3.1.7 on 2021-03-20 14:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candy_delivery_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='code',
        ),
        migrations.AddField(
            model_name='region',
            name='number',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courier',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='courier',
            name='type',
            field=models.CharField(choices=[('foot', 'Foot'), ('bike', 'Bike'), ('car', 'Car')], max_length=4),
        ),
        migrations.AlterField(
            model_name='region',
            name='courier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candy_delivery_app.courier'),
        ),
    ]
