# Generated by Django 3.1.7 on 2021-03-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candy_delivery_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_duration',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
