# Generated by Django 3.1.7 on 2021-03-22 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candy_delivery_app', '0003_auto_20210320_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courier',
            name='type',
        ),
        migrations.CreateModel(
            name='CourierType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_time', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('foot', 'Foot'), ('bike', 'Bike'), ('car', 'Car')], max_length=4)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candy_delivery_app.courier')),
            ],
        ),
    ]
